FILE_PATH = '<csv_file_path>'
username = 'neo4j'
password = 'password'
URI = 'bolt://localhost:7687'
SEPARATOR = '$'
LEFT_ENTITY = 'L'
RIGHT_ENTITY = 'R'
RELATIONSHIP = 'Rel'
LABEL = 'label'
ID ='id'
EQUALS ='='
APPEND_R = 'r.+'
APPEND_L ='l.+'